
export const GET_IMAGES_PENDING = 'GET_IMAGES_PENDING';
export const GET_IMAGES_FULFILLED = 'GET_IMAGES_FULFILLED';
export const GET_IMAGES_REJECTED = 'GET_IMAGES_REJECTED';

export const PREV_IMAGE = 'PREV_IMAGE';
export const NEXT_IMAGE = 'NEXT_IMAGE';

